export const apiList = {
  fetchTrending: '/v2/customer/new-and-trending-products',
  fetchPopularCategory: '/v2/category/popular-categories',
  categoryFetch: '/v2/category/category-levels',
  productFetch: '/v2/customer/list-products',
  productListFilter: '/v2/customer/filter-list',
  bannerFetch: '/banner/fetchBanner/homepage',
  brandListFetch: '/brand/fetchBrand',
  newAndTrending: '/sellerProducts/newAndTrending',
  productDetails: '/v3/customer/product-details/',
  makeOnlinePayment: '/v3/customer/createPayment',
  addToCart: '/v2/customer/add-to-cart',
  fetchCartList: '/v2/customer/get-cart-list',
  checkoutProducts: '/v2/customer/cart-checkout',
  deleteCartProduct: '/v2/customer/delete-cart-item',
  placeOrderProduct: '/v2/customer/place-order',
  fetchDeliveryLocation: '/v2/customer/addressList',
  getAutoCompleteList: '/v2/search/autocomplete/',
  fetchDeliverySlots: '/v2/customer/slots',


  sendOtp: '/v2/common/send-otp',
  verifyOtp: '/v2/common/verify-otp',
  signUp: '/v2/customer/sign-up',
  login: '/v2/customer/login',
  userDetails: '/v2/customer/userDetails',
  updateUserData: '/v2/customer/updateDetails',
  uploadprofileImage: '/v2/customer/uploadProfileImage',
  sendChangeEmailOtp: '/v2/customer/changeEmailOtpSend',
  submitChangeEmail: '/v2/customer/changeEmailVerify',
  sendChangeMobileOtp: '/v2/customer/changeMobileOtpSend',
  submitChangeMobile: '/v2/customer/changeMobileVerify',
  addEditAddress: '/v2/customer/addEditAddress',
  addressList: '/v2/customer/addressList',
  makePrimaryAddress: '/v2/customer/setPrimaryAddress/',
  deleteAddress: '/v2/customer/deleteAddress/',
  wishList: '/v2/customer/wishList',
  orderList: '/v2/customer/get-orders',
  addWishList: '/v2/wishlist/add',
  removeWishList: '/v2/wishlist/remove',
  orderDetails: '/v2/customer/get-orders/',
  wishListCount: '/v2/wishlist/count'
};
